apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "greenops.labels" (dict "context" . "component" .Values.commandDelegator.name "name" .Values.commandDelegator.name) | nindent 4 }}
  name: {{ .Values.commandDelegator.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.commandDelegator.replicas }}
  selector:
    matchLabels:
      {{- include "greenops.selectorLabels" (dict "context" . "name" .Values.commandDelegator.name) | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "greenops.labels" (dict "context" . "component" .Values.commandDelegator.name "name" .Values.commandDelegator.name) | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.commandDelegator.name }}
      containers:
        - env:
            - name: ORG_NAME
              value: {{ .Values.common.orgName }}
            - name: SERVING_PORT
              value: "{{ .Values.commandDelegator.port }}"
            {{ if .Values.common.disableTLS }}
            - name: DISABLE_TLS
              value: "true"
            {{ end }}
            - name: ATLAS_DB_ADDRESS
              value: {{ .Values.common.db.address }}
            {{ if .Values.common.db.password.enabled }}
            - name: ATLAS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.db.password.secretName }}
                  key: {{ .Values.common.db.password.key }}
                  optional: false
            {{ end }}
          image: {{ .Values.commandDelegator.image }}
          imagePullPolicy: {{ .Values.commandDelegator.imagePullPolicy }}
          name: {{ .Values.commandDelegator.name }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.commandDelegator.port }}
          ports:
            - containerPort: {{ .Values.commandDelegator.port }}
          resources: {}
      {{ if .Values.common.imageCredentials.enabled }}
      imagePullSecrets:
        - name: {{ .Values.common.imageCredentials.imagePullSecret }}
      {{ end }}
      restartPolicy: {{ .Values.commandDelegator.restartPolicy}}
