{{ if .Values.common.kubernetes.generateRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.commandDelegator.name }}
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["core"]
    resources:
      - namespaces
    verbs: [ "get" ]
  - apiGroups: ["", "core"]
    resources:
      - secrets
      - configmaps
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.commandDelegator.name }}
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.commandDelegator.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.commandDelegator.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
