apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "greenops.labels" (dict "context" . "component" .Values.commandDelegator.name "name" .Values.commandDelegator.name) | nindent 4 }}
  name: {{ .Values.commandDelegator.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  ports:
    - name: {{ quote .Values.commandDelegator.port }}
      port: {{ .Values.commandDelegator.port }}
      targetPort: {{ .Values.commandDelegator.port }}
  selector:
    {{- include "greenops.selectorLabels" (dict "context" . "name" .Values.commandDelegator.name) | nindent 4 }}
