{{ if .Values.common.db.deployRedis }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "greenops.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  ports:
    - name: {{ quote .Values.redis.name }}
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    {{- include "greenops.selectorLabels" (dict "context" . "name" .Values.redis.name) | nindent 4 }}
{{ end }}
