apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "dex.labels" (dict "context" . "component" .Values.dex.name "name" "cm") | nindent 4 }}
data:
{{- range $key, $value := .Values.common.sso.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
