apiVersion: v1
kind: Secret
metadata:
  name: greenops-sso
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "dex.labels" (dict "context" . "component" .Values.dex.name "name" "greenops-sso") | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Values.common.namespace "greenops-sso") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $clientId := (get $secretData "client-id") | default ("greenops-sso" | b64enc) }}
  {{- $clientSecret := (get $secretData "client-secret") | default (randAlphaNum 32 | b64enc) }}
  client-id: {{ $clientId | quote }}
  client-secret: {{ $clientSecret | quote }}
