apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dex.name }}
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "dex.labels" (dict "context" . "component" .Values.dex.name "name" .Values.dex.name) | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.dex.servicePortHttpName }}
    protocol: TCP
    port: {{ .Values.dex.servicePortHttp }}
    targetPort: http
  - name: {{ .Values.dex.servicePortGrpcName }}
    protocol: TCP
    port: {{ .Values.dex.servicePortGrpc }}
    targetPort: grpc
  selector:
    {{- include "dex.selectorLabels" (dict "context" . "name" .Values.dex.name) | nindent 4 }}
