apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.dex.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "dex.serviceAccountName" . }}
  namespace: {{ .Values.common.namespace }}
{{- if .Values.dex.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.dex.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "dex.labels" (dict "context" . "component" .Values.dex.name "name" .Values.dex.name) | nindent 4 }}
