apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.server.name }}
  strategy: {}
  template:
    metadata:
      labels:
        service: {{ .Values.server.name }}
    spec:
      serviceAccountName: {{ .Values.server.name }}
      containers:
        - env:
            - name: ORG_NAME
              value: {{ .Values.common.orgName }}
            - name: SERVER_EXTERNAL_URI
              value: {{ .Values.common.server.greenopsUrl }}
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.license.secretName }}
                  key: {{ .Values.common.license.key }}
                  optional: false
            - name: ATLAS_DB_ADDRESS
              value: {{ .Values.common.db.address }}
            {{ if .Values.common.db.password.enabled }}
            - name: ATLAS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.db.password.secretName }}
                  key: {{ .Values.common.db.password.key }}
                  optional: false
            {{ end }}
            {{ if .Values.common.sso.enabled }}
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.sso.secretName }}
                  key: {{ .Values.common.sso.secret.clientIdKey }}
                  optional: false
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.sso.secretName }}
                  key: {{ .Values.common.sso.secret.clientSecretKey }}
                  optional: false
            - name: SSO_REDIRECT_URI
              value: "{{ .Values.common.server.greenopsUrl }}/oauth2/callback"
            - name: SSO_ISSUER_URI
              value: {{ .Values.common.sso.argoCdUrl }}/api/dex
            {{ end }}
          image: {{ .Values.server.image }}
          imagePullPolicy: {{ .Values.server.imagePullPolicy }}
          name: {{ .Values.server.name }}
          ports:
            - containerPort: {{ .Values.server.port }}
          resources: {}
      imagePullSecrets:
        - name: {{ .Values.common.imagePullSecret }}
      restartPolicy: {{ .Values.server.restartPolicy}}
