apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "greenops.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "greenops.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "greenops.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.server.name }}
      containers:
        - env:
            - name: ORG_NAME
              value: {{ .Values.common.orgName }}
            - name: SERVER_EXTERNAL_URI
              value: https://{{ .Values.common.server.greenopsUrl }}
            - name: COMMAND_DELEGATOR_SERVER_ENDPOINT
              {{ if .Values.common.disableTLS }}
              value: http://greenops-commanddelegator.greenops.svc.cluster.local:{{ .Values.commandDelegator.port }}
              {{ else }}
              value: https://greenops-commanddelegator.greenops.svc.cluster.local:{{ .Values.commandDelegator.port }}
              {{ end }}
            {{ if .Values.common.disableTLS }}
            - name: DISABLE_TLS
              value: "true"
            {{ end }}
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.license.secretName }}
                  key: {{ .Values.common.license.key }}
                  optional: false
            - name: ATLAS_DB_ADDRESS
              value: {{ .Values.common.db.address }}
            {{ if .Values.common.db.password.enabled }}
            - name: ATLAS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.db.password.secretName }}
                  key: {{ .Values.common.db.password.key }}
                  optional: false
            {{ end }}
            - name: SERVING_PORT
              value: "{{ .Values.server.targetPort }}"
            - name: JUMP_SERVER_SSH_PORT
              value: {{ .Values.common.server.tunnelingPort }}
            {{ if .Values.common.sso.enabled }}
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.sso.secretName }}
                  key: {{ .Values.common.sso.secret.clientIdKey }}
                  optional: false
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.sso.secretName }}
                  key: {{ .Values.common.sso.secret.clientSecretKey }}
                  optional: false
            - name: SSO_REDIRECT_URI
              value: "https://{{ .Values.common.server.greenopsUrl }}/oauth2/callback"
            - name: SSO_ISSUER_URI
              value: https://{{ .Values.common.server.greenopsUrl }}/api/dex
            - name: SSO_PROVIDER_URI
              value: http://{{ .Values.dex.name }}:{{ .Values.dex.servicePortHttp }}
            {{ end }}
          image: {{ .Values.server.image }}
          imagePullPolicy: {{ .Values.server.imagePullPolicy }}
          name: {{ .Values.server.name }}
          {{ if .Values.common.disableTLS }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.server.port }}
          {{ end }}
          ports:
            - containerPort: {{ .Values.server.targetPort }}
          resources: {}
      {{ if .Values.common.imageCredentials.enabled }}
      imagePullSecrets:
        - name: {{ .Values.common.imageCredentials.imagePullSecret }}
      {{ end }}
      restartPolicy: {{ .Values.server.restartPolicy}}
