apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.server.name }}-cluster
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: [ "create" ]
  - apiGroups: ["pipeline.greenopsinc.io"]
    resources:
      - pipelines
      - pipelines/status
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.server.name }}-gitcred
  namespace: gitcred
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["", "apps", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - namespaces
      - configmaps
      - deployments
      - pods
      - services
      - pipelines
      - pipelines/status
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.server.name }}-gitcred
  namespace: gitcred
subjects:
  - kind: ServiceAccount
    name: {{ .Values.server.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.server.name }}-gitcred
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.server.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.server.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.server.name }}-cluster
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.server.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.server.name }}-cluster
  apiGroup: rbac.authorization.k8s.io
