apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  type: NodePort
  ports:
    - name: {{ quote .Values.server.port }}
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      nodePort: {{ .Values.server.nodePort }}
  selector:
    service: {{ .Values.server.name }}
