apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "greenops.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
  name: {{ .Values.server.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  {{ if .Values.server.enableLoadBalancer }}
  type: LoadBalancer
  {{ end }}
  ports:
    - name: {{ quote .Values.server.port }}
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.targetPort }}
  selector:
    {{- include "greenops.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 4 }}
