{{ if .Values.common.kubernetes.generateRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["core"]
    resources:
      - namespaces
    verbs: [ "get" ]
  - apiGroups: ["", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - configmaps
      - pipelines
      - pipelines/status
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.controller.name }}-pipelines
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["pipeline.greenopsinc.io"]
    resources:
      - pipelines
      - pipelines/status
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.controller.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.controller.name }}-pipelines
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.controller.name }}-pipelines
  apiGroup: rbac.authorization.k8s.io
{{ end }}
