apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.namespace }}-prometheus-conf
  namespace: {{ .Values.common.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'greenops'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        basic_auth:
          username: {{ .Values.prometheus.auth.username }}
          password: {{ .Values.prometheus.auth.password }}
        scrape_interval: 5s
        static_configs:
          - targets: [{{ .Values.prometheus.greenopsServerUrl }}]
      - job_name: 'workflows'
        scrape_interval: 5s
        static_configs:
          - targets: [{{ .Values.prometheus.workflowsServerUrl }}]
