apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.metricsServer.name }}
  name: {{ .Values.metricsServer.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  ports:
    - name: {{ quote .Values.metricsServer.port }}
      port: {{ .Values.metricsServer.port }}
      targetPort: {{ .Values.metricsServer.port }}
  selector:
    service: {{ .Values.metricsServer.name }}
