apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - core
      - argoproj.io
      - rbac.authorization.k8s.io
      - apiextensions.k8s.io
      - apps
    resources:
      - namespaces
      - secrets
      - workflows
      - templates
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - serviceaccounts
      - clusterroles
      - clusterrolebindings
      - rolebindings
      - configmaps
      - customresourcedefinitions
      - roles
      - services
      - deployments
      - statefulsets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
