apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        service: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - env:
            - name: WORKFLOW_TRIGGER_SERVER_ADDR
              value: https://{{ .Values.common.greenopsServer.url }}
            - name: COMMAND_DELEGATOR_URL
              value: https://{{ .Values.common.commandDelegator.url }}
            - name: CLUSTER_NAME
              value: {{ .Values.common.clusterName }}
            - name: NAMESPACE
              value: {{ .Values.namespace }}
            - name: ARGO_WORKFLOWS_URL
              value: {{ .Values.common.argo.workflows.url }}
            - name: ARGOCD_URL
              value: {{ .Values.common.argo.cd.internalUrl }}
            - name: GREENOPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.greenopsApiKey.secretName }}
                  key: {{ .Values.common.greenopsApiKey.key }}
                  optional: false
            {{- range .Values.extraEnvs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ .Values.name }}
          resources: {}
      imagePullSecrets:
        - name: {{ .Values.common.imagePullSecret }}
      restartPolicy: {{ .Values.restartPolicy}}
