apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}
  namespace: greenops
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - rbac.authorization.k8s.io
    resources:
      - secrets
      - serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-argocd-management
  namespace: argocd
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - rbac.authorization.k8s.io
      - core
      - apps
    resources:
      - namespaces
      - secrets
      - serviceaccounts
      - rolebindings
      - roles
      - configmaps
      - services
      - deployments
      - statefulsets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-argocd-management-clusterscope
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - rbac.authorization.k8s.io
      - apiextensions.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-workflow-management
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - argoproj.io
    resources:
      - namespaces
      - workflows
      - templates
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-argocd-management-clusterscope
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-argocd-management-clusterscope
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-workflow-management
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-workflow-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-argocd-management
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}-argocd-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
