{{ if .Values.common.kubernetes.generateRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}
  namespace: greenops
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-argocd-management
  namespace: argocd
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - rbac.authorization.k8s.io
      - core
      - apps
    resources:
      - secrets
      - serviceaccounts
      - rolebindings
      - roles
      - configmaps
      - services
      - deployments
      - statefulsets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-argocd-management-clusterscope
rules:
  # GreenOps deploys Argo CD's ClusterRole for the application controller.
  # Due to permission escalation prevention rules with Kubernetes RBAC, GreenOps requires all verbs to manage this Argo CD resource.
  # GreenOps ONLY uses this privilege to create/update/patch Argo CD's application controller's ClusterRole, nothing else.
  - verbs:
      - "*"
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
  - verbs:
      - create
      - update
      - patch
    apiGroups:
      - apiextensions.k8s.io
      - rbac.authorization.k8s.io
    resources:
      - customresourcedefinitions
      - clusterrolebindings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-workflow-management
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - templates
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-argocd-management-clusterscope
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-argocd-management-clusterscope
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-workflow-management
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-workflow-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-argocd-management
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}-argocd-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
