apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.configmapName }}
  namespace: {{ .Values.common.namespace }}
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access":"proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": {{ .Values.grafana.prometheusUrl }},
          "version": 1
        }
      ]
    }
