apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.common.namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   {{ squote .Values.grafana.port }}
spec:
  selector:
    app: {{ .Values.grafana.name }}
  type: NodePort
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
