common:
  namespace: greenops

prometheus:
  name: prometheus
  image: prom/prometheus
  port: 9090
  auth:
    username: ""
    password: ""
  greenopsServerUrl: ""
  workflowsServerUrl: ""

grafana:
  name: prometheus
  image: grafana/grafana:latest
  prometheusUrl: "http://prometheus-service.greenops.svc.cluster.local:9090"
  port: 3000
  configmapName: grafana-datasources
