common:
  clusterName: ""
  imagePullSecret: regcred
  greenopsApiKey:
    secretName: greenops-apikey-secret
    key: apikey
  commandDelegator:
    url: "greenops-commanddelegator.greenops.svc.cluster.local:8080"
  greenopsServer:
    url: "greenops-server.greenops.svc.cluster.local:8080"
  argo:
    workflows:
      url: ""

name: greenops-daemon
namespace: greenops
argoNamespace: argo
orgName: org
image: docker.io/greenopsinc/godaemon:v0.10.0
replicas: 1
imagePullPolicy: IfNotPresent
restartPolicy: Always
