apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["", "core"]
    resources:
      - secrets
      - namespaces
      - configmaps
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelineRepoServer.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.pipelineRepoServer.name }}
  apiGroup: rbac.authorization.k8s.io
