apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.pipelineRepoServer.name }}
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.pipelineRepoServer.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.pipelineRepoServer.name }}
  strategy: {}
  template:
    metadata:
      labels:
        service: {{ .Values.pipelineRepoServer.name }}
    spec:
      serviceAccountName: {{ .Values.pipelineRepoServer.name }}
      containers:
          - image: {{ .Values.pipelineRepoServer.image }}
            env:
              - name: ATLAS_DB_ADDRESS
                value: {{ .Values.common.db.address }}
              {{ if .Values.common.db.password.enabled }}
              - name: ATLAS_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.common.db.password.secretName }}
                    key: {{ .Values.common.db.password.key }}
                    optional: false
              {{ end }}
            imagePullPolicy: {{ .Values.pipelineRepoServer.imagePullPolicy }}
            name: {{ .Values.pipelineRepoServer.name }}
            ports:
              - containerPort: {{ .Values.pipelineRepoServer.port }}
            resources: {}
      imagePullSecrets:
        - name: {{ .Values.common.imagePullSecret }}
      restartPolicy: {{ .Values.pipelineRepoServer.restartPolicy}}
