{{ if .Values.common.kubernetes.generateRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.pipelineRepoServer.name }}-gitcred
  namespace: gitcred
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
rules:
  - apiGroups: ["core"]
    resources:
      - namespaces
    verbs: [ "get" ]
  - apiGroups: ["", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - configmaps
      - pipelines
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.pipelineRepoServer.name }}-gitcred
  namespace: gitcred
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelineRepoServer.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.pipelineRepoServer.name }}-gitcred
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelineRepoServer.name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.pipelineRepoServer.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
