{{ if .Values.common.kubernetes.generateServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pipelineRepoServer.name }}
  namespace: {{ .Values.common.namespace }}
{{ end }}
