arguments:
  parameters:
    - name: deploy-to-dev-argocd-version
      value: v2.0.5
    - name: deploy-to-dev-application-name
      value: guestbook-app-dev
    - name: deploy-to-dev-revision
      value: master
    - name: deploy-to-dev-flags
      value: --
    - name: deploy-to-dev-argocd-server-address
      value: argocd.greenops.io
    - name: deploy-to-dev-argocd-credentials-secret
      value: argocd-user
    - name: deploy-to-staging-argocd-version
      value: v2.0.5
    - name: deploy-to-staging-application-name
      value: guestbook-app-staging
    - name: deploy-to-staging-revision
      value: master
    - name: deploy-to-staging-flags
      value: --
    - name: deploy-to-staging-argocd-server-address
      value: argocd.greenops.io
    - name: deploy-to-staging-argocd-credentials-secret
      value: argocd-user
