apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.imagePullSecret }}
  namespace: {{ .Values.common.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
