{{ if .Values.server.sso.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.server.sso.secretName }}
  namespace: {{ .Values.common.namespace }}
data:
  client-id: {{ b64enc .Values.server.sso.clientId }}
  client-secret: {{ b64enc .Values.server.sso.clientSecret }}
{{ end }}
