common:
  db:
    address: redisserver.greenops.svc.cluster.local:6379
    password:
      enabled: false
      secretName: ""
      key: ""
    # Currently only GCP is supported for automated PersistentVolume creation. Other cloud providers have to be done manually.
    usePersistentVolume: false
  server:
    greenopsUrl: ""
  sso:
    enabled: false
    argoCdUrl: ""
    secretName: greenops-sso
    secret:
      clientIdKey: client-id
      clientSecretKey: client-secret
  namespace: greenops
  orgName: org
  imagePullSecret: regcred
  license:
    secretName: greenops-license
    key: license

server:
  name: greenops-server
  image: docker.io/greenopsinc/goserver:v0.10.0
  replicas: 1
  imagePullPolicy: Always
  restartPolicy: Always
  nodePort: 30007
  port: 8080

controller:
  name: greenops-controller
  image: docker.io/greenopsinc/controller:v0.10.0
  replicas: 1
  imagePullPolicy: Always
  restartPolicy: Always
  metrics:
    bindAddress: localhost:8082
    healthProbeBindAddress: localhost:8083

pipelineRepoServer:
  name: greenops-reposerver
  image: docker.io/greenopsinc/pipelinereposerver:v0.10.0
  nodePort: 32522
  port: 8080
  replicas: 1
  imagePullPolicy: Always
  restartPolicy: Always

commandDelegator:
  name: greenops-commanddelegator
  image: docker.io/greenopsinc/commanddelegator:v0.10.0
  nodePort: 32533
  port: 8080
  replicas: 1
  imagePullPolicy: Always
  restartPolicy: Always

metricsServer:
  name: greenops-metricsserver
  image: docker.io/greenopsinc/greenops-metrics-server:v0.10.0
  nodePort: 32544
  port: 2112
  replicas: 1
  imagePullPolicy: Always
  restartPolicy: Always

redis:
  name: redisserver
  image: redis
  port: 6379
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volume:
    name: redis-storage
    persistentVolume:
      name: redis-pv
      labels:
        topology.kubernetes.io/region: ""
        topology.kubernetes.io/zone: ""
        type: ""
      gcePersistentDisk:
        pdName: ""
        fsType: ""
    persistentVolumeClaim:
      name: redis.pvc
