common:
  namespace: greenops
  orgName: org
  argoCdUrl: ""
  licenseKey: ""
  dbAddress: ""
  usePersistentVolume: false
  imagePullSecret: regcred
  imageCredentials:
    registry: "https://index.docker.io/v1/"
    username: ""
    password: ""
    email: ""

server:
  name: greenops-server
  externalUrl: ""
  image: docker.io/greenopsinc/goserver:v0.10.0-b2
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodePort: 30007
  port: 8080
  role:
    apiGroups: ["", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - namespaces
      - configmaps
      - pipelines
      - pipelines/status
  sso:
    secretName: greenops-sso
    clientId: ""
    clientSecret: ""

controller:
  name: greenops-controller
  image: docker.io/greenopsinc/controller:v0.10.0-b2
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  metrics:
    bindAddress: localhost:8082
    healthProbeBindAddress: localhost:8083
  role:
    apiGroups: ["", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - namespaces
      - configmaps
      - pipelines
      - pipelines/status

pipelineRepoServer:
  name: greenops-reposerver
  image: docker.io/greenopsinc/pipelinereposerver:v0.10.0-b2
  nodePort: 32522
  port: 8084
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  role:
    apiGroups: ["", "core"]
    resources:
      - secrets
      - namespaces
      - configmaps

commandDelegator:
  name: greenops-commanddelegator
  image: docker.io/greenopsinc/commanddelegator:v0.10.0-b2
  nodePort: 32533
  port: 8085
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  role:
    apiGroups: ["", "core"]
    resources:
      - secrets
      - namespaces
      - configmaps

metricsServer:
  name: greenops-metrics-server
  image: docker.io/greenopsinc/greenops-metrics-server:v0.10.0-b2
  nodePort: 32544
  port: 2112
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  role:
    apiGroups: ["", "core", "pipeline.greenopsinc.io"]
    resources:
      - secrets
      - namespaces
      - configmaps
      - pipelines
      - pipelines/status

redis:
  name: redisserver
  image: redis
  port: 6379
  replicas: 1
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volume:
    name: redis-storage
    persistentVolume:
      name: redis-pv
      labels:
        topology.kubernetes.io/region: ""
        topology.kubernetes.io/zone: ""
        type: ""
      gcePersistentDisk:
        pdName: ""
        fsType: ""
    persistentVolumeClaim:
      name: redis.pvc
